# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
program1 = Program.create(title: "Downton Abbey")
program2 = Program.create(title: "Sense and Sensibility")
program3 = Program.create(title: "The Paradise")
program4 = Program.create(title: "Stage Beauty")
program5 = Program.create(title: "Upstairs/Downstairs")
program6 = Program.create(title: "The New World")
program7 = Program.create(title: "Daniel Deronda")
program8 = Program.create(title: "The Portrait of a Lady")
program9 = Program.create(title: "Carrington")
program10 = Program.create(title: "Quills")
program11 = Program.create(title: "Bleak House")
program12 = Program.create(title: "A Little Princess")
program13 = Program.create(title: "The House of Mirth")
program14 = Program.create(title: "Pride and Prejudice")
program15 = Program.create(title: "Little Dorrit")
program16 = Program.create(title: "The Remains of the Day")
program17 = Program.create(title: "Elizabeth")
program18 = Program.create(title: "A Room with a View")
program19 = Program.create(title: "The Forsythe Saga")
program20 = Program.create(title: "Brideshead Revisited")

user1 = User.create(name: "Jen", email: "jen@jen.com", password: "beef")
user2 = User.create(name: "Chris", email: "chris@chris.com", password: "beef")
user3 = User.create(name: "Kristy", email: "kristy@kristy.com", password: "beef")
user4 = User.create(name: "John", email: "john@john.com", password: "beef")
user5 = User.create(name: "Nancy", email: "nancy@nancy.com", password: "beef")

post1 = Post.create(title: "I <3 Matthew Crawley", post: "Matthew, a rose by any other name could not smell so sweet", program_id: 1)
post2 = Post.create(title: "Emma rocks", post: "If there is any entertainment figure on this earth greater than Emma Thompson I know not who he or she be. ", program_id: 2)
post3 = Post.create(title: "An intoxicating love story set in England's first department store in the 1870s.", post: "Will Moray choose love or locale?", program_id: 3)
post4 = Post.create(title: "Sexual Politics of Men in Drag", post: "In this underrated film, Claire Danes stars as one of the first women to break into acting during the reign of King Charles II. As you may know, in that era women’s roles were played by men. Danes’ fictional Maria shakes that up, all the while striking up a romance with Billy Crudup’s Ned. ", program_id: 4)
post5 = Post.create(title: "I live upstairs but my heart is downstairs.", post: "The lives and fortunes of the Bellamy family and their below-stairs servant staff at 165 Eaton Place play out against the social, political and historical backdrop of Edwardian London from 1903 to 1930.", program_id: 5)
post6 = Post.create(title: "Slow, Strange and Beautiful", post: "This movie, like all Terrence Malick movies, is as strange as it is beautiful. The pacing is slow, but the shots are gorgeous. There’s a lot of long, searching looks exchanged by Q’orianka Kilcher and Colin Farrell, very little physical contact. In that sense it seems almost like it was directed by a teenage girl.", program_id: 6)
post7 = Post.create(title: "Why isn’t Romola Garai a big star?", post: "The 2002 BBC adaptation of George Eliot’s novel starred Hugh Dancy as the titular character, but the performance that stays with you is Romola Garai’s as the spoiled-but-eventually-impoverished Gwendolen Harleth. A predecessor of pop culture’s great spoiled rich girls, like Buffy‘s Cordelia Chase, Gwendolen is willful and bright and suffers terribly for it. ", program_id: 7)
post8 = Post.create(title: "Do not pass go, do not get married, women! ", post: "Jane Campion’s adaptation of the Henry James book is hard to come by, these days. And when it was released the reviews were middling, largely because people always give Jane Campion middling reviews. Because they are wrong about Jane Campion! And wrong about the idea than an explicitly feminist aesthetic is somehow too “political” to be an aesthetic! Anyway. Nicole Kidman stars as Isabel Archer and John Malkovich as the man who marries her and subsequently ruins her life. ", program_id: 8)
post9 = Post.create(title: "Bloomsbury - a nice place to visit", post: "Emma Thompson triumphs again as the slightly androgynous painter Dora Carrington, a figure on the UK’s Bloomsbury movement, who falls in an idiosyncratic sort of love with Jonathan Pryce’s Lytton Strachey. Strachey was… really quite gay. ", program_id: 9)
post10 = Post.create(title: "Ribald, funny, hypnotic", post: "Philip Kaufman and Doug Wright’s film about the Marquis de Sade is the kind of thing you don’t want to sit around watching with your parents or your children. That is, unless you and your parents or your children are happy to openly discuss necrophilia. But particularly with Geoffrey Rush in the lead role, the film makes it easy to understand why de Sade’s writing have had the hold they have over the culture. ", program_id: 10)
post11 = Post.create(title: "Be haunted for years", post: "Gillian Anderson’s performance as the haunted Lady Dedlock, who gave up a lovechild at birth and has lived on to regret it. Who knew, when we all watched The X-Files, so long ago, that Scully would become one of the great treasures of historical dramas? (She’ll reappear below on this list.) No one. Anna Maxwell Martin, starring as the good but lost protagonist Esther, will also eat your heart.", program_id: 11)
